export const GET_APIDATA = 'GET_APIDATA'
export const CREATE_ODER = 'CREATE_ODER'
export const SWITCH_BUN = "SWITCH_BUN"
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const SWITCH_INGREDIENT_DETAILS = 'SWITCH_INGREDIENT_DETAILS'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SORTED_INGREDIENTS = 'SORTED_INGREDIENTS'