export const APIDATA_REQUEST : 'APIDATA_REQUEST' = 'APIDATA_REQUEST'
export const CREATE_ODER : 'CREATE_ODER' ='CREATE_ODER' 
export const SWITCH_BUN : "SWITCH_BUN" ="SWITCH_BUN"
export const ADD_INGREDIENT : 'ADD_INGREDIENT' ='ADD_INGREDIENT'
export const SWITCH_INGREDIENT_DETAILS : 'SWITCH_INGREDIENT_DETAILS' ='SWITCH_INGREDIENT_DETAILS'
export const REMOVE_INGREDIENT : 'REMOVE_INGREDIENT' ='REMOVE_INGREDIENT'
export const SORTED_INGREDIENTS : 'SORTED_INGREDIENTS' ='SORTED_INGREDIENTS'

export const REGISTER_USER : 'REGISTER_USER' ='REGISTER_USER'
export const SIGN_IN_USER : 'SIGN_IN_USER' ='SIGN_IN_USER'
export const LOG_OUT : 'LOG_OUT' ='LOG_OUT'
export const AUTHORIZATION_USER : 'AUTHORIZATION_USER' ='AUTHORIZATION_USER'
export const AUTH_CHECKED : 'AUTH_CHECKED' ='AUTH_CHECKED'

export const WS_CONNECTION_START : 'WS_CONNECTION_START' ='WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS : 'WS_CONNECTION_SUCCESS' ='WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR : 'WS_CONNECTION_ERROR' ='WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED : 'WS_CONNECTION_CLOSED' ='WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE : 'WS_GET_MESSAGE' ='WS_GET_MESSAGE';
export const wsActions = {
    wsInit: WS_CONNECTION_START,
    onOpen: WS_CONNECTION_SUCCESS,
    onClose: WS_CONNECTION_CLOSED,
    onError: WS_CONNECTION_ERROR,
    onMessage: WS_GET_MESSAGE,
  }
